### ISSUE TITLE
Tests if run with "gradlew test", fail because of usage of javax.xml.ws.http.HTTPException

### ISSUE THREAD

**Issue by siboXD** [iuginP/pps-17-cw-mp#22]
We should create an equivalent (or better) **exception class** and put it in *core* subproject

Exctract from gradle log:

```Discovery starting.
Discovery completed in 4 seconds, 492 milliseconds.
Run starting. Expected test count is: 63
*** RUN ABORTED *** (4 seconds, 602 milliseconds)
  java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: javax/xml/ws/http/HTTPException
  at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
  at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
  at org.scalatest.tools.ConcurrentDistributor.waitUntilDone(ConcurrentDistributor.scala:50)
  at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1325)
  at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1031)
  at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1010)
  at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1500)
  at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
  at org.scalatest.tools.Runner$.main(Runner.scala:827)
  at org.scalatest.tools.Runner.main(Runner.scala)
  ...
  Cause: java.lang.NoClassDefFoundError: javax/xml/ws/http/HTTPException
  at it.cwmp.testing.server.rooms.RoomsWebServiceTesting.beforeEach(RoomsWebServiceTesting.scala:32)
  at org.scalatest.BeforeAndAfterEach.runTest(BeforeAndAfterEach.scala:220)
  at org.scalatest.BeforeAndAfterEach.runTest$(BeforeAndAfterEach.scala:214)
  at it.cwmp.testing.server.rooms.RoomsWebServiceTesting.runTest(RoomsWebServiceTesting.scala:20)
  at org.scalatest.AsyncFunSpecLike.$anonfun$runTests$1(AsyncFunSpecLike.scala:474)
  at org.scalatest.AsyncSuperEngine.$anonfun$runTestsInBranch$1(AsyncEngine.scala:434)
  at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
  at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
  at scala.collection.immutable.List.foldLeft(List.scala:86)
  at org.scalatest.AsyncSuperEngine.traverseSubNodes$1(AsyncEngine.scala:419)
  ...
  Cause: java.lang.ClassNotFoundException: javax.xml.ws.http.HTTPException
  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
  at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
  at it.cwmp.testing.server.rooms.RoomsWebServiceTesting.beforeEach(RoomsWebServiceTesting.scala:32)
  at org.scalatest.BeforeAndAfterEach.runTest(BeforeAndAfterEach.scala:220)
  at org.scalatest.BeforeAndAfterEach.runTest$(BeforeAndAfterEach.scala:214)
  at it.cwmp.testing.server.rooms.RoomsWebServiceTesting.runTest(RoomsWebServiceTesting.scala:20)
  at org.scalatest.AsyncFunSpecLike.$anonfun$runTests$1(AsyncFunSpecLike.scala:474)
  at org.scalatest.AsyncSuperEngine.$anonfun$runTestsInBranch$1(AsyncEngine.scala:434)
  at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
  ...

> Task :core:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:test'.
```

**Comment by siboXD** [comment]
Credo in generale tutti gli usi, diano problemi, il primo errore lo trova nell'autenticazione ma forse solo perchè è il primo alfabeticamente;

Il problema a me lo dà se eseguo dalla root del progetto il comando "gradlew test" che dovrebbe eseguire tutti i test; provate anche voi.

In ogni caso avevo già in mente di proporre un cambiamento, perchè importare questa classe esterna mi sembra una dipendenza inutile, molto meglio crearsi una nostra HttpException (*che magari contenga anche un messaggio di errore* visto che quella non può)

**Comment by siboXD** [comment]
E' un problema che si presenta se si esegue gradle con Java 10, probabilmente in Java 10 le dipendenze javafx non fanno èiù parte del jdk e sono esterne, per questo non trovava la classe.

Con una classe di errore nostra abbiamo più controllo su questa cosa ;) :+1:
